name: bloom-filter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   # clone repo into runner environment

    - name: "Build and run tests"
      run: |
        cd bloom-filter
        make
        make clean